### ISSUE TITLE
Daily reports are wrong if compared to iTunes Connect - Sales and Trends

### ISSUE THREAD

**Issue by SPDEX** [omz/AppSales-Mobile#275]
The daily values are completely wrong. Check iTunes Connect - Sales and Trends

**Comment by dave256** [comment]
I've noticed that often the CSV file you download from iTunes Connect doesn't match what they show on the website. The few times I've checked it by downloading the file on my Mac, unzipping it, and inspecting it manually, the results match what AppSales-Mobile shows (not surprisingly since it downloads the file and uses it). The problem of course is which data do you trust - the downloaded file or what the website shows? @SPDEX please see if the downloaded file also matches what you're seeing. I haven't complained to Apple and can't easily tell which one is correct based on my monthly deposits as they're close enough to what AppSales-Mobile shows that I've always chalked it up to currency fluctuations.

**Comment by omz** [comment]
You also might want to check if you have "Local" or "UTC" time selected in iTunes Connect. The AppSales numbers should match "Local" time.

**Comment by SPDEX** [comment]
Yes, if I set the time zone to Local, they are the same.
